### ISSUE TITLE
Bot not responding to messages.

### ISSUE THREAD

**Issue by RKartik9** [tushgaurav/TimApple#7]
Hi there, 
I have recently forked this code and tried it on my own test server, but the bot seems to be online and not respond to messages.

**Comment by tushgaurav** [comment]
Hi Kartik,
As of Sep 1, 2022, Discord introduced [breaking changes](https://discord.com/developers/docs/change-log#sep-1-2022) which affect message content reading for new bots. If you want the same availabilities you have to turn on the Privileged Intents in the OAuth2 section.
Also, add this code to your bot -
```python
intents = discord.Intents.default()
intents.message_content = True
client = discord.Client(intents=intents)
```
This will now allow the bot/application to use the message_content.
